# -*- coding: utf-8 -*-
"""01_Least_Square_Method_실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125lwFbircs190eHYHVdXPGRl8o5MnDIm
"""

# -*- coding: utf-8 -*-
import numpy as np

# x 값과 y값
x=[2, 4, 6, 8]
y=[81, 93, 91, 97]

mx = np.mean(x)
my = np.mean(y)

print(mx)
print(my)

# 분모 만들기

divisor = sum([(i - mx) ** 2 for i in x])
print(divisor)

# 분자 만들기

def top(x, mx, y, my):
  d = 0
  for i in range(len(x)):
    d += (x[i] - mx) * (y[i] - my)
  return d

dividend = top(x, mx, y, my)

print(dividend)

# 기울기 a 구하기

a = dividend / divisor

print(a)

# y절편 b 구하기

b = my - (a * mx)

print(b)